# Use the specified Python image
FROM python:3.10-bullseye

# Set the working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY ./app/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the code
COPY ./app /app

# Run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
