# Use Node.js image
FROM node:18.17.1

# Set working directory
WORKDIR /app

# Install dependencies
COPY ./package.json ./package-lock.json ./
RUN npm install

# Copy only the src directory
COPY ./src /app/src

# Start the app
CMD ["npm", "run", "dev"]