# Use Node.js image
FROM node:18.17.1

# Set working directory
WORKDIR /app

# Install dependencies
COPY ./package.json ./package-lock.json ./
RUN npm install

# Copy the rest of the code
COPY . .

# Start the app
CMD ["npm", "run", "dev"]
